Awesome books: refactor to use JavaScript classes
fbclh/awesome-books pull request #2
Opened 2022-02-07 22:03 UTC by fbclh

2022-02-07 23:56 UTC, mateo951 requested changes
### Hi Team, 

📝👌 **Your project highlights** 🔥😎 
- General Requirements ✔
- JS Best Practices ✔

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-07 23:56 UTC, mateo951 commented on index.js
> +const removeElement = (element) => {
Awesome use of arrow functions 👌

2022-02-07 23:56 UTC, mateo951 commented on index.js
> +}
Fantastic 🙌 Proper use of JavaScript classes instead of objects and arrays as expected!

2022-02-07 23:56 UTC, mateo951 commented on index.js
> +    this.list.forEach((el) => {
As you can see in the following image there is a tiny issue that is preventing the user to add a new book 😥

![image](https://user-images.githubusercontent.com/15807343/152891947-dd788a25-894e-4a28-8bd2-6ccb14191cb2.png)

Please fix this issue so your project meets the project requirements 📝 Your app should be able to add and remove books 🤓 Kindly make sure the refactoring did not introduce bugs to the app in other areas as well!

2022-02-08 15:41 UTC, od-c0d3r approved these changes
Asslam Alaikum Team @fbclh @franklinben23 ,😊

Hi👋🏽, Your project is complete!  There is nothing else to say other than... it's time to merge it 😎 

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 21:42 UTC, merged